version: '3.5'
services:
  nginx:
    container_name: ngnix
    build: ./nginx/
    restart: always
    volumes:
     - WordPress:/var/www/html
    depends_on:
      - wordpress
      - adminer
    ports:
      - "443:443"
      - "80:80"
    networks:
      - mynetwork

  wordpress:
    container_name: wordpress
    build: ./wordpress/
    restart: always
    depends_on:
      - mariadb
    volumes:
     - WordPress:/var/www/html
    networks:
     - mynetwork
    env_file: .env

  adminer:
    container_name: Adminer     # Name redirect to IP -> 172.X.X.Z
    build: adminer/.            # Build the dockerfile in ./adminer/Dockerfile 
    restart: always             # Restart the container if it has stopped
    networks:
      - mynetwork               # Use mynetwork for communicate with mariadb
    env_file: .env

  mariadb:
    container_name: Mariadb
    build: mariadb/.
    restart: always
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql
    env_file: .env
 
# NETWORK
networks:
  mynetwork:
    name : mynetwork
    driver : bridge

# VOLUME
volumes:
  WordPress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/bbird/data/website   # Create this folder in the Makefile

  db:
    driver: local
    driver_opts:                          # Options specific to the driver
      type: 'none'
      o: 'bind'
      device: /home/bbird/data/db        # Create this folder in the Makefile

